apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: pgdb
    group: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgdb
  template:
    metadata:
      labels:
        app: pgdb
    spec:
      containers:
        - name: pgdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
               name: postgres-secret
