apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: spring-jpa
    group: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-jpa
  template:
    metadata:
      labels:
        app: spring-jpa
    spec:
      containers:
      - name: spring-jpa
        image: swa23/springboot-docker-app:0.0.5
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
